function [data] = readOutput(filename)
% [data] = readOutput(filename) read the output files generated by Aerodyn.
% The output of the function readOutputis a structure file named "data",
% which reads as
% data.RPM = rotation per minute
% data.TSR = tip speed ratio
% data.P = Power output of the turbine, in Watt
% data.T = Thrust force on the rotor (in Newton)
% data.Cp = Power coefficient
% data.Cq = Torque coefficient
% data.Ct = Thrust coefficient
% data.meanU = mean wind speed (in m/s)
%
% Author: E Cheynet - UiB - 15/03/2022

data0 = dir(['outputFiles/',filename,'.*.out']);
N = numel(data0);

Cp = zeros(1,N);
Ct = zeros(1,N);
Cq = zeros(1,N);
P = zeros(1,N);
T = zeros(1,N);
RPM = zeros(1,N);
TSR = zeros(1,N);
meanU= zeros(1,N);
% str2double(regexp(xx, '\d*', 'match'))

for ii=1:N
    %     dummyName = [data0(ii).folder,'/',data0(ii).name];
    %     fid = fopen(dummyName);   %Open the output files in a loop depending on number of cases
    
    dummyName = ['outputFiles/',filename,'.' num2str(ii) '.out'];
    fid = fopen( dummyName );
    Read_OutData = textscan(fid, '%f %f %f %f %f %f %f %f %f', 'HeaderLines',9);
    OutData=Read_OutData(1,:);
    OutData= cell2mat(OutData);
    N = round(size(OutData,1)/2);
    RPM(ii) = nanmedian(OutData(N:end,2));
    TSR(ii)= nanmedian(OutData(N:end,3));
    P(ii) = nanmedian(OutData(N:end,4));
    T(ii) = nanmedian(OutData(N:end,5));
    Cp(ii)=nanmedian(OutData(N:end,6));
    Ct(ii)=nanmedian(OutData(N:end,7));
    Cq(ii)=nanmedian(OutData(N:end,8));
    fclose(fid);
    
    % Get the mean wind speed
    dummy = importfile(dummyName,5,5, ['%s%s%*[^\n]'],{';',':'});
    dummy = char(dummy{2});
    meanU(ii) = str2double(regexp(dummy,'\d+\.?\d*','match'));
end

[meanU,ind]=sort(meanU);

data.RPM = RPM(ind);
data.TSR = TSR(ind);
data.P = P(ind);
data.T = T(ind);
data.Cp = Cp(ind);
data.Cq = Cq(ind);
data.Ct = Ct(ind);
data.meanU = meanU(ind);

  
end

