function [data] = readOutput(filename)
% [data] = readOutput(filename) read the output files generated by Aerodyn.
% The output of the function readOutputis a structure file named "data",
% which reads as
% data.RPM = rotation per minute
% data.TSR = tip speed ratio
% data.P = Power output of the turbine, in Watt
% data.T = Thrust force on the rotor (in Newton)
% data.Cp = Power coefficient
% data.Cq = Torque coefficient
% data.Ct = Thrust coefficient
% data.meanU = mean wind speed (in m/s)
%
% Author: E Cheynet - UiB - 15/03/2022

data0 = dir(['outputFiles/',filename,'.*.out']);
Nsamples = numel(data0);

Cp = zeros(1,Nsamples);
Ct = zeros(1,Nsamples);
Cq = zeros(1,Nsamples);
P = zeros(1,Nsamples);
T = zeros(1,Nsamples);
RPM = zeros(1,Nsamples);
TSR = zeros(1,Nsamples);
meanU= zeros(1,Nsamples);
Cd= zeros(Nsamples,9);
% str2double(regexp(xx, '\d*', 'match'))

for ii=1:Nsamples
        dummyName = [data0(ii).folder,'/',data0(ii).name];
    %     fid = fopen(dummyName);   %Open the output files in a loop depending on number of cases
    
    % dummyName = ['outputFiles/',filename,'.' num2str(ii) '.out'];
    % fid = fopen( dummyName );
    % Read_OutData = textscan(fid, '%f %f %f %f %f %f %f %f %f', 'HeaderLines',9);
    % OutData=Read_OutData(1,:);
    % OutData= cell2mat(OutData);

    T0=readtable(dummyName,'FileType','text');
    indT = find(T0.Time>7);

    RPM(ii) = median(T0.RtSpeed(indT),'omitnan');
    TSR(ii)= median(T0.RtTSR(indT),'omitnan');
    P(ii) = median(T0.RtAeroPwr(indT),'omitnan');
    T(ii) = median(T0.RtAeroFxh(indT),'omitnan');
    Cp(ii)=median(T0.RtAeroCp(indT),'omitnan');
    Ct(ii)=median(T0.RtAeroCt(indT),'omitnan');
    Cq(ii)=median(T0.RtAeroCq(indT),'omitnan');
    
    for jj=1:9
    Cd(ii,jj)=median(T0.(['B1N',num2str(jj),'Cd'])(indT),'omitnan');
    end
    
    % Get the mean wind speed
    dummy = importfile(dummyName,5,5, ['%s%s%*[^\n]'],{';',':'});
    dummy = char(dummy{2});
    meanU(ii) = str2double(regexp(dummy,'\d+\.?\d*','match'));
end

[meanU,ind]=sort(meanU);

data.RPM = RPM(ind);
data.TSR = TSR(ind);
data.P = P(ind);
data.T = T(ind);
data.Cp = Cp(ind);
data.Cq = Cq(ind);
data.Cd = Cd(ind,:);
data.Ct = Ct(ind);
data.meanU = meanU(ind);

  
end

